version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports: ["11434:11434"]
    volumes:
      - ./model_files:/model_files  # Mount the directory with the trained mode
    #pull_policy: always
    tty: true
    restart: unless-stopped
    networks:
      - kong-net  
    entrypoint: ["/bin/sh", "/model_files/run_ollama.sh"] # Loading the finetuned Mistral with the GGUF file
  
  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    ports: ["3000:8080"]
    volumes:
      - ollama-webui:/app/backend/data
    depends_on:
      - ollama
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
    networks:
      - kong-net
    restart: unless-stopped

volumes:
  ollama: {}
  ollama-webui: {}

networks:
  kong-net:
    external: true
