version: '3'
services:
  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001" # Redis UI
    networks:
      - kong-net
networks:
  kong-net:
    external: true

